version: 0.2

env:
  variables:
    SONAR_LOGIN: "7a16f9f11e724d5672fd1466d5848f45d3353f3d"
    SONAR_HOST: "http://13.235.76.152:9000"
    #You should use parameter-store here instead

phases:
  pre_build:
    commands:
      - yum update -y
      - yum install -y maven
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST
